import type {
  AgentRecord,
  AgentRole,
  ApprovalRecord,
  AgentGitSessionRecord,
  CheckRunRecord,
  DiffFileRecord,
  DiffSectionRecord,
  MessageRecord,
  RepositoryInspection,
  RollCallAgentStatusRecord,
  SwarmDraft,
  TaskRecord,
  TimelineEventRecord,
  TouchedFileRecord,
  WorkspaceAgentSession,
  WorkspaceSession
} from "./domain";

function slugify(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-");
}

function nowOffset(minutesAgo = 0): string {
  return new Date(Date.now() - minutesAgo * 1000 * 60).toISOString();
}

function createAgentStatus(role: AgentRole): AgentRecord["status"] {
  if (role === "Coordinator") {
    return "planning";
  }

  if (role === "Scout") {
    return "running";
  }

  if (role === "Reviewer") {
    return "waiting";
  }

  if (role === "Tester") {
    return "idle";
  }

  return "waiting";
}

function createAgentRecord(
  repository: RepositoryInspection,
  swarmId: string,
  role: AgentRole,
  index: number
): AgentRecord {
  const agentKey = `${slugify(role)}-${index + 1}`;

  return {
    id: `agent:${agentKey}`,
    swarmId,
    name: `${role} ${index + 1}`,
    role,
    status: createAgentStatus(role),
    branchName: `agent/${agentKey}`,
    worktreePath: `${repository.path.replace(/\\/g, "/")}/.forgeswarm/${agentKey}`,
    touchedFiles: []
  };
}

function createTouchedFiles(role: AgentRole, agentId: string): TouchedFileRecord[] {
  const byRole: Record<AgentRole, string[]> = {
    Coordinator: ["plans/swarm-plan.md", "reports/roll-call.md"],
    Builder: ["src/workspace/orchestration-feed.tsx", "src/state/swarm-engine.ts"],
    Scout: ["notes/repo-map.md", "notes/key-entrypoints.md"],
    Reviewer: ["reviews/diff-review.md", "reviews/regression-risks.md"],
    Tester: ["checks/lint-summary.md", "checks/build-gate.md"]
  };

  return byRole[role].map((path, index) => ({
    agentId,
    path,
    changeType: index === 0 ? "modified" : "created"
  }));
}

function createDiffFiles(role: AgentRole, touchedFiles: TouchedFileRecord[]): DiffFileRecord[] {
  return touchedFiles.map((file, index) => ({
    path: file.path,
    changeType: file.changeType,
    additions: 8 + index * 5 + (role === "Builder" ? 11 : role === "Reviewer" ? 4 : 2),
    deletions: index === 0 ? 2 + (role === "Builder" ? 3 : 1) : 1,
    note:
      role === "Builder"
        ? "Primary implementation lane change prepared for review."
        : role === "Scout"
          ? "Discovery artifact feeding the builder handoff."
          : role === "Reviewer"
            ? "Review notes documenting risk or scope."
            : role === "Tester"
              ? "Gate output informing merge readiness."
              : "Coordinator audit artifact for the operator console."
  }));
}

function createDiffSections(role: AgentRole, diffFiles: DiffFileRecord[]): DiffSectionRecord[] {
  return [
    {
      id: `${role.toLowerCase()}:section:1`,
      title: role === "Builder" ? "Implementation Surface" : "Lane Output",
      summary:
        role === "Builder"
          ? "Core file edits scoped for supervised review."
          : "Supporting artifacts generated by this lane remain visible to the operator.",
      risk: role === "Builder" ? "medium" : role === "Reviewer" || role === "Tester" ? "low" : "medium",
      files: diffFiles.map((file) => file.path)
    },
    {
      id: `${role.toLowerCase()}:section:2`,
      title: "Regression Focus",
      summary:
        role === "Tester"
          ? "Validation output needs to stay aligned with the reviewer gate."
          : "Review this lane against the protected branch and current coordinator plan.",
      risk: role === "Builder" ? "high" : "medium",
      files: diffFiles.slice(0, 1).map((file) => file.path)
    }
  ];
}

function createDefaultAgentGitSession(agent: AgentRecord, baseBranch = "main"): AgentGitSessionRecord {
  return {
    agentId: agent.id,
    strategy: "worktree",
    branchName: agent.branchName,
    worktreePath: agent.worktreePath,
    baseBranch,
    status: "planning",
    conflictState: "unknown",
    exists: false,
    note: "Git isolation has not been synchronized yet.",
    lastSyncedAt: null,
    resetAvailable: false,
    rollbackAvailable: false
  };
}

function createPendingApproval(agent: AgentRecord, swarmId: string): ApprovalRecord {
  const requestedAt = nowOffset(2);

  return {
    id: `approval:${agent.id}`,
    swarmId,
    agentId: agent.id,
    branchName: agent.branchName,
    status: "pending",
    requestedByAgentId: agent.id,
    requestedAt,
    decidedAt: null,
    decidedBy: null,
    summary: `Awaiting operator review for ${agent.branchName}.`,
    comment: null,
    auditTrail: [
      {
        id: `approval:${agent.id}:audit:1`,
        createdAt: requestedAt,
        actor: "Coordinator",
        action: "queued",
        summary: `${agent.name} entered the supervised merge queue.`
      }
    ]
  };
}

function createTasks(role: AgentRole, agentId: string, swarmId: string): TaskRecord[] {
  const taskTemplates: Record<AgentRole, Array<Pick<TaskRecord, "title" | "summary" | "status">>> = {
    Coordinator: [
      {
        title: "Decompose operator prompt into agent lanes",
        summary: "Translate the top-level task into a scout-first, review-gated execution plan.",
        status: "running"
      },
      {
        title: "Run roll call before review handoff",
        summary: "Poll the swarm and confirm lane status before merge review begins.",
        status: "todo"
      }
    ],
    Builder: [
      {
        title: "Implement assigned subtask",
        summary: "Pick up the scoped builder handoff once repo context is available.",
        status: "todo"
      },
      {
        title: "Publish diff summary for reviewer",
        summary: "Leave the reviewer with a narrow, inspectable change surface.",
        status: "todo"
      }
    ],
    Scout: [
      {
        title: "Inspect repository structure",
        summary: "Map the relevant directories, files, and framework signals before builders move.",
        status: "running"
      },
      {
        title: "Brief builders on important files",
        summary: "Surface entrypoints, touched-file clusters, and likely review anchors.",
        status: "todo"
      }
    ],
    Reviewer: [
      {
        title: "Audit incoming diffs for regressions",
        summary: "Check the builder change set against the current workspace state.",
        status: "todo"
      },
      {
        title: "Keep merge gate closed until checks pass",
        summary: "Only clear the review lane once tester output is coherent.",
        status: "todo"
      }
    ],
    Tester: [
      {
        title: "Run configured validation checks",
        summary: "Progress lint, typecheck, and build states as the swarm approaches review.",
        status: "todo"
      },
      {
        title: "Publish gate summary",
        summary: "Report the current check state back to the coordinator and reviewer lanes.",
        status: "todo"
      }
    ]
  };

  return taskTemplates[role].map((task, index) => ({
    id: `${agentId}:task:${index + 1}`,
    swarmId,
    agentId,
    ...task
  }));
}

function createTimeline(role: AgentRole, agentId: string): TimelineEventRecord[] {
  const details: Record<AgentRole, string> = {
    Coordinator: "Coordinator reserved the control lane and is preparing the first decomposition pass.",
    Builder: "Builder lane is waiting on scout context before file edits begin.",
    Scout: "Scout lane is gathering repository structure and stack signals.",
    Reviewer: "Reviewer lane is staged and waiting for a diff worth auditing.",
    Tester: "Tester lane is idle until checks are greenlit by the current swarm preferences."
  };

  return [
    {
      id: `${agentId}:event:1`,
      agentId,
      timestamp: nowOffset(7),
      title: `${role} lane ready`,
      detail: details[role],
      tone: role === "Scout" ? "info" : "neutral"
    }
  ];
}

function createChecks(role: AgentRole, agentId: string, swarmId: string): CheckRunRecord[] {
  const names = ["lint", "typecheck", "build"] as const;

  return names.map((name) => ({
    id: `${agentId}:check:${name}`,
    swarmId,
    agentId,
    name,
    status: role === "Tester" ? "pending" : "pending",
    summary:
      role === "Tester"
        ? `${name} is queued behind the current orchestration stage.`
        : `${name} will be reported through the tester lane when the merge gate opens.`
  }));
}

function createMessage(
  swarmId: string,
  direction: MessageRecord["direction"],
  body: string,
  options: {
    agentId?: string;
    authorLabel: string;
    recipientLabel: string | null;
    idSuffix: string;
    minutesAgo?: number;
  }
): MessageRecord {
  return {
    id: `${swarmId}:message:${options.idSuffix}`,
    swarmId,
    agentId: options.agentId,
    direction,
    authorLabel: options.authorLabel,
    recipientLabel: options.recipientLabel,
    body,
    createdAt: nowOffset(options.minutesAgo ?? 0)
  };
}

function createAgentSession(
  repository: RepositoryInspection,
  swarmId: string,
  role: AgentRole,
  index: number
): WorkspaceAgentSession {
  const agent = createAgentRecord(repository, swarmId, role, index);
  const touchedFiles = createTouchedFiles(role, agent.id);
  const diffFiles = createDiffFiles(role, touchedFiles);
  const diffSections = createDiffSections(role, diffFiles);
  const tasks = createTasks(role, agent.id, swarmId);
  const timeline = createTimeline(role, agent.id);
  const additions = diffFiles.reduce((total, file) => total + file.additions, 0);
  const deletions = diffFiles.reduce((total, file) => total + file.deletions, 0);

  agent.touchedFiles = touchedFiles.map((file) => file.path);

  return {
    agent,
    git: createDefaultAgentGitSession(agent, repository.branch ?? "main"),
    touchedFiles,
    tasks,
    timeline,
    terminal: {
      id: `${agent.id}:terminal`,
      agentId: agent.id,
      title: `${slugify(role)}-session-${index + 1}`,
      cwd: repository.path,
      lines: [
        {
          id: `${agent.id}:terminal:1`,
          kind: "command",
          text: `$ forgeswarm.agent --role ${slugify(role)} --workspace "${repository.path}"`
        },
        {
          id: `${agent.id}:terminal:2`,
          kind: "stdout",
          text: `> ${role} lane booted with ${touchedFiles.length} focus files and ${tasks.length} staged tasks.`
        }
      ]
    },
    diffSummary: {
      id: `${agent.id}:diff`,
      agentId: agent.id,
      title: `${agent.name} proposal`,
      summary:
        role === "Builder"
          ? `${agent.name} prepared a scoped implementation diff for reviewer and tester gating.`
          : `${agent.name} published supporting artifacts for the supervised review loop.`,
      filesChanged: diffFiles.length,
      additions,
      deletions
    },
    diffFiles,
    diffSections,
    checks: createChecks(role, agent.id, swarmId),
    approval: createPendingApproval(agent, swarmId),
    comments: [
      {
        id: `${agent.id}:comment:1`,
        author: role === "Reviewer" ? "Reviewer" : "Coordinator",
        body:
          role === "Reviewer"
            ? "Diff review stays blocked until builders and testers produce coherent state."
            : "Keep this lane visible so the operator can supervise without opening side terminals.",
        createdAt: nowOffset(3)
      }
    ]
  };
}

function createInitialMessages(agents: WorkspaceAgentSession[], swarmId: string): MessageRecord[] {
  const coordinator = agents.find((entry) => entry.agent.role === "Coordinator") ?? agents[0];
  const scout = agents.find((entry) => entry.agent.role === "Scout");
  const primaryBuilder = agents.find((entry) => entry.agent.role === "Builder");

  return [
    createMessage(
      swarmId,
      "system",
      "Swarm booted in mock orchestration mode. The operator remains the approval authority.",
      {
        authorLabel: "System",
        recipientLabel: "Operator",
        idSuffix: "boot",
        minutesAgo: 5
      }
    ),
    createMessage(
      swarmId,
      "agent",
      "Start with repository reconnaissance and surface the most important files before builder lanes advance.",
      {
        agentId: coordinator.agent.id,
        authorLabel: coordinator.agent.name,
        recipientLabel: scout?.agent.name ?? "Scout lane",
        idSuffix: "coordinator-directive",
        minutesAgo: 4
      }
    ),
    createMessage(
      swarmId,
      "agent",
      "Initial stack detection is stable. I will brief the builder lanes once the entrypoints are mapped.",
      {
        agentId: scout?.agent.id,
        authorLabel: scout?.agent.name ?? "Scout lane",
        recipientLabel: primaryBuilder?.agent.name ?? "Builder lane",
        idSuffix: "scout-brief",
        minutesAgo: 2
      }
    )
  ];
}

export function createMockWorkspaceSession(
  repository: RepositoryInspection,
  swarmDraft: SwarmDraft
): WorkspaceSession {
  const swarmId = `swarm:${slugify(repository.name)}`;
  const agents = swarmDraft.roles.map((role, index) => createAgentSession(repository, swarmId, role, index));
  const coordinator = agents.find((entry) => entry.agent.role === "Coordinator") ?? agents[0];

  return normalizeWorkspaceSession({
    id: `workspace:${slugify(repository.name)}`,
    repository,
    swarmDraft,
    status: "running",
    orchestrationStage: "coordinating",
    activeAgentId: coordinator.agent.id,
    coordinatorPlan: [
      {
        id: "plan:1",
        title: "Inspect repository context and assign lanes",
        status: "in-progress",
        ownerRole: "Scout",
        note: "Scout should complete repo reconnaissance before builder lanes push diffs."
      },
      {
        id: "plan:2",
        title: "Execute builder work in visible parallel lanes",
        status: "planned",
        ownerRole: "Builder",
        note: "Builders should publish inspectable diffs and terminal traces, not hidden state."
      },
      {
        id: "plan:3",
        title: "Clear review and test gates before merge queue",
        status: "planned",
        ownerRole: "Reviewer",
        note: "Reviewer and tester lanes gate the path to approval review."
      }
    ],
    globalTimeline: [
      {
        id: "timeline:1",
        timestamp: nowOffset(6),
        title: "Swarm created",
        detail: `Coordinator accepted the operator prompt and provisioned ${swarmDraft.agentCount} agent lanes.`,
        tone: "info"
      },
      {
        id: "timeline:2",
        timestamp: nowOffset(1),
        title: "Workspace hydrated",
        detail: "The operator console is ready to stream mock orchestration events.",
        tone: "success"
      }
    ],
    messages: createInitialMessages(agents, swarmId),
    lastRollCall: null,
    gitIsolation: null,
    agents
  })!;
}

function inferOrchestrationStage(workspace: WorkspaceSession): WorkspaceSession["orchestrationStage"] {
  if (workspace.status === "review") {
    return "awaiting-approval";
  }

  if (workspace.agents.some((entry) => entry.agent.role === "Tester" && entry.agent.status === "running")) {
    return "testing";
  }

  if (workspace.agents.some((entry) => entry.agent.role === "Reviewer" && entry.agent.status === "running")) {
    return "reviewing";
  }

  if (workspace.agents.some((entry) => entry.agent.role === "Builder" && entry.agent.status === "running")) {
    return "building";
  }

  if (workspace.agents.some((entry) => entry.agent.role === "Scout" && entry.agent.status === "running")) {
    return "scouting";
  }

  return "coordinating";
}

function createFallbackRollCallStatuses(workspace: WorkspaceSession): RollCallAgentStatusRecord[] {
  return workspace.agents.map((entry) => ({
    agentId: entry.agent.id,
    agentName: entry.agent.name,
    status: entry.agent.status,
    note: `${entry.agent.name} is visible in the operator console.`
  }));
}

export function normalizeWorkspaceSession(workspace: WorkspaceSession | null | undefined): WorkspaceSession | null {
  if (!workspace) {
    return null;
  }

  return {
    ...workspace,
    orchestrationStage: workspace.orchestrationStage ?? inferOrchestrationStage(workspace),
    messages: workspace.messages ?? [],
    agents: workspace.agents.map((entry) => ({
      ...entry,
      terminal: {
        ...entry.terminal,
        lines: entry.terminal.lines ?? []
      },
      touchedFiles: entry.touchedFiles ?? [],
      tasks: entry.tasks ?? [],
      timeline: entry.timeline ?? [],
      diffFiles: entry.diffFiles ?? [],
      diffSections: entry.diffSections ?? [],
      checks: entry.checks ?? [],
      approval: entry.approval ?? createPendingApproval(entry.agent, entry.agent.swarmId),
      comments: entry.comments ?? [],
      git: entry.git ?? createDefaultAgentGitSession(entry.agent, workspace.repository.branch ?? "main"),
      agent: {
        ...entry.agent,
        touchedFiles: entry.agent.touchedFiles ?? entry.touchedFiles.map((file) => file.path)
      }
    })),
    globalTimeline: workspace.globalTimeline ?? [],
    coordinatorPlan: workspace.coordinatorPlan ?? [],
    activeAgentId:
      workspace.agents.find((entry) => entry.agent.id === workspace.activeAgentId)?.agent.id ??
      workspace.agents[0]?.agent.id ??
      workspace.activeAgentId,
    gitIsolation: workspace.gitIsolation ?? null,
    lastRollCall:
      workspace.lastRollCall && workspace.lastRollCall.agentStatuses.length > 0
        ? workspace.lastRollCall
        : workspace.lastRollCall
          ? {
              ...workspace.lastRollCall,
              agentStatuses: createFallbackRollCallStatuses(workspace)
            }
          : null
  };
}

export function getWorkspaceAgentSession(
  workspace: WorkspaceSession,
  agentId: string
): WorkspaceAgentSession {
  return normalizeWorkspaceSession(workspace)?.agents.find((entry) => entry.agent.id === agentId) ?? workspace.agents[0]!;
}

export function getWorkspaceTouchedFiles(workspace: WorkspaceSession, agentId?: string): TouchedFileRecord[] {
  const normalized = normalizeWorkspaceSession(workspace);

  if (!normalized) {
    return [];
  }

  if (agentId) {
    return getWorkspaceAgentSession(normalized, agentId).touchedFiles;
  }

  return normalized.agents.flatMap((entry) => entry.touchedFiles);
}
